services:
  app:
    image: ghcr.io/itskovacs/trip:1.36.0
    ports:
      - "8002:8000"
    volumes:
      - trip_storage:/app/storage
    command: ["fastapi", "run", "/app/trip/main.py", "--host", "0.0.0.0"]

volumes:
  trip_storage:
